#!/bin/zsh
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
export SUBLIME=subl
export EDITOR="$SUBLIME --wait"
export VISUAL=$EDITOR
export LSCOLORS="exfxcxdxbxegedabagacad"
export DEFAULT_USER=mclayton

# 256 Colors
[[ "$TERM" == "xterm" ]] && export TERM=xterm-256color

# Add General aliases.
if [ -f ~/dotfiles/aliases/generalAliases ]; then
    source ~/dotfiles/aliases/generalAliases
fi

# Setup Paths
export PATH=~/dotfiles/bin:$PATH
export PATH=/opt/clang/bin:$PATH
export PATH=/opt/qtcreator/bin:$PATH
export PYTHONPATH=~/dotfiles/python:$PYTHONPATH


# Turn bell off:
setterm -blength 0
